components/layout/main-navigation.js, components/layout/main-navigation.module.css, package-lock.json, package.json, pages/index.js, pages/recipe-list/index.js, pages/recipe-list/recipe-list.module.css, utils/mongodb-utils.js
I created a navbar that will appear on the home page and in the recipe-list page
=> Add Navbar

pages/recipe-list/index.js, pages/recipe-list/recipe-list.module.css
created a load more button in the Recipe-List page that displays more recipes when clicked, it also shows the number of recipes left to be displayed. The button will disappears when all the recipes have been displayed.
=> Add LoadMoreButton 

components/layout/main-navigation.js, pages/recipe-list/index.js
I styled the images so that only one image appears, I also added a grid.
=> Style Images

.gitignore, next.config.js, pages/api/recipe/[recipe-details].js, pages/api/recipe/[recipeDetails].js, utils/mongodb-utils.js
1. Added testing URL for development and production in the next.config file
2. Added next.config file to gitignore
3. Changed File from recipe-details to recipeDetails
4. Added API route for a single recipe collection
5. Added a single recipe helper function in utils
=> Add testing url env

components/layout/main-navigation.js, pages/index.js, pages/recipe-list/index.js
I edited the navbar. I enabled the user to search for a specific recipe based on a title search and I also removed the "contacts" & "about" tags in the nav bar.
=> Add Search Bar Functionality

utils/mongodb-utils.js
- Update the number of recipes that can be fetch per load
=> Update to 100 recipes per load

pages/recipe-list/[recipe-details].js, pages/recipe-list/[recipeDetails].js
1. Added a getServerSideProps function to add data in the single recipe page route.
=> Added data for single recipe

components/recipe-list.js, components/recipe-list.module.css, styles/globals.css, tailwind.config.js
Updated recipe list items with dynamic linking to detail pages.
=> Recipe list

components/home-page/home-page.js, components/home-page/home-page.module.css, components/recipe-cart/recipecard.js, components/recipe-description/recipe-description.js, components/recipe-list.module.css, pages/index.js, pages/recipe-list/index.js
1. Created a Home Page Component
2. Added a Button to the page to allow dynamic routing
3. Created a CSS Module for the page to center align the content
4. Rendered the Home Page component to the main Page
=> Created Dynamic routing for the Home page.

utils/mongodb-utils.js
1. Added documentation 
2. Added the Allergen function to utils
3. Added the Categories function to utils
=> Added allergens and categories functon to utils

components/layout/main-navigation.js, components/layout/search-bar.js, components/recipe-list.js
I added more styling to the search filter and load more button
=> Update Recipe List Page

components/recipe-cart/recipecard.js
Changed time format in recipe details
=> Formatted time

package-lock.json, package.json, pages/_app.js, pages/api/auth/[auth0].js, pages/index.js
1. Installed dotenv library.
2. installed auth0.
3. Added auth API route page.
4. Added UserProvider to _app.
5. Added simple login logic.
=> Adding users logs

components/recipe-description/recipe-description.js, components/recipe-description/update-description/update-description.js, package-lock.json
Separating functionality for editing with visibility of description.
=> fixing update description component

components/recipe-cart/allergens/allergens-ingredient.js, components/recipe-cart/recipecard.js, components/recipe-cart/update-recipe/description.js, pages/recipe-list/[recipeDetails].js
Added allergens to description
=> Added allergens to recipe description

components/recipe-list.js
the user can now load 20 recipes when they click the load more button instead of 4 recipes .
=> Load 20 Recipes instead of 4

components/recipe-cart/recipecard.js, components/recipe-list.js
I removed the recipecart.module.css and added comments to the recipe list code
=> replace css styling with tailwind css styling  and added documentation

components/home-page/home-page.js, components/recipe-cart/recipecard.js, components/recipe-cart/update-recipe/description.js, components/recipe-list.js, components/tags/tags-display.js, components/ui-utils/card.js, pages/_app.js, pages/recipe-details/[recipeDetails].js, tailwind.config.js
In this pull-request, I added minimal responsive behavior to the recipe description page and also added a favorites button to the lists .
=> Responsive recipe details view

components/recipe-list.js, pages/404.js
Display the total count of recipes that match the search
=> Display Search Result Total

components/category-filter/category-filter.js, components/recipe-list.js, package-lock.json, pages/api/categories.js, pages/index.js, pages/search/index.js
- Added a search page
- Created a search bar 
- Created categories buttons 
- Added a functionality to search using the categories
=> Added Page routing to the search page.

components/ui-utils/FavoriteButton.js, pages/api/favourite.js, pages/api/unfavour.js, utils/mongodb-utils.js
Added remove favourite functionality.
=> Remove from favourite

components/navigation/navbar.js, components/recipeList/recipeList.js, components/ui-utils/RecipePreviewCard.js, pages/recipeList/[recipeList].js, pages/search/[searchQuery].js
I made peace to the name of the branch by adding the highlighting functionality. The branch features a few changes to the preview card component making it dynamic to whether it is searching or just in the recipe list page.
=> Add highlighting functionality

components/layout/searchBar.js, components/navigation/navbar.js, components/recipeList/recipeList.js, components/ui-utils/filteringForm.js, components/ui-utils/navLink.js, styles/globals.css, utils/mongodb-utils.js
Redesign the navbar to be more responsive and have a more traditional nav look to it.
=> Navbar redesign

components/layout/searchBar.js, components/navigation/navbar.js, components/recipeList/recipeList.js, components/ui-utils/filteringForm.js, components/ui-utils/searchSort.js, package-lock.json, package.json, pages/recipeList/[recipeList].js
Just implement the Ui for the search functionality
=> Search restructuring

components/ui-utils/FavoriteButton.js, pages/recipeDetails/[recipeDetails].js, pages/recipeList/[recipeList].js, utils/mongodb-utils.js
Improved the favourite. The favourite from favourite, recipe list and recipe detail are now in sync.
=> Improving favourites

components/filtering/allFilter.js, components/filtering/filterByIngredients.js, components/ui-utils/filteringForm.js, components/ui-utils/overlay/overlay.js
=> used useState instead of useRef

components/context/recipeContext.js, components/ui-utils/overlay/overlay.js, next.config.js, pages/_app.js
Added context provider that will store the state of the filter object.
=>  UseContext

components/layout/searchBar.jsx, components/navigation/navbar.jsx, components/recipeList/recipeList.jsx, components/ui-utils/filteringForm.jsx, components/ui-utils/searchSort.jsx
I updated The navbar. The search bar is no longer on display unless the user clicks on the search icon. I also added a dropdown button for login/sign-up.
=> Navigation

components/recipeCard/recipeCard.jsx, components/recipeCard/updateRecipe/instructions.jsx
Add error handling to the instruction load.
=> Error instruction load#7

components/context/recipeContext.jsx, components/filtering/filterByCategory.jsx, components/filtering/filterByTags.jsx, components/recipeCard/allergens/allergensIngredient.jsx, components/recipeCard/recipeCard.jsx, components/recipeCard/updateRecipe/instructions.jsx, package-lock.json, package.json
Fixed the filtering button and changed its state and fixed the allergens
=> Filtering overlay button

components/ui-utils/sortingForm.jsx, pages/recipes/index.jsx
Fixed the sorting options that they update the UI of the recipeList
=> Sorting options
